/**
 * hyprlog - Flexible logging library
 *
 * C-ABI bindings for hyprlog.
 *
 * Basic usage:
 *   HyprlogContext* ctx = hyprlog_init();
 *   hyprlog_info(ctx, "MAIN", "Application started");
 *   hyprlog_free(ctx);
 *
 * Or with simple setup (no config file):
 *   HyprlogContext* ctx = hyprlog_init_simple(HYPRLOG_LEVEL_DEBUG, 1);
 *   hyprlog_debug(ctx, "NET", "Connecting...");
 *   hyprlog_free(ctx);
 */


#ifndef HYPRLOG_H
#define HYPRLOG_H

#pragma once

/* Generated with cbindgen:0.28.0 */

/* Auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Log level constants for FFI.
 */
#define HYPRLOG_LEVEL_TRACE 0

#define HYPRLOG_LEVEL_DEBUG 1

#define HYPRLOG_LEVEL_INFO 2

#define HYPRLOG_LEVEL_WARN 3

#define HYPRLOG_LEVEL_ERROR 4

/**
 * Opaque context holding the logger and error state.
 */
typedef struct HyprlogContext HyprlogContext;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Creates a new hyprlog context with default configuration.
 *
 * Loads config from `~/.config/hypr/hyprlog.conf` if present,
 * otherwise uses defaults.
 *
 * Returns `NULL` on failure. Use `hyprlog_get_last_error` to retrieve error.
 */
struct HyprlogContext *hyprlog_init(void);

/**
 * Creates a new hyprlog context with configuration from the specified path.
 *
 * # Safety
 * `config_path` must be a valid null-terminated UTF-8 string or `NULL`.
 * If `NULL`, uses default config path.
 *
 * Returns `NULL` on failure.
 */
struct HyprlogContext *hyprlog_init_with_config(const char *config_path);

/**
 * Creates a minimal logger with only terminal output (no config file).
 *
 * Useful for quick setup without configuration.
 *
 * # Arguments
 * * `level` - Minimum log level (0=trace, 1=debug, 2=info, 3=warn, 4=error)
 * * `colors` - Enable ANSI colors (1=true, 0=false)
 */
struct HyprlogContext *hyprlog_init_simple(int level, int colors);

/**
 * Frees a hyprlog context.
 *
 * # Safety
 * `ctx` must be a valid pointer returned by `hyprlog_init*` or `NULL`.
 * After this call, `ctx` is invalid and must not be used.
 */
void hyprlog_free(struct HyprlogContext *ctx);

/**
 * Logs a message at the specified level.
 *
 * # Safety
 * - `ctx` must be a valid context pointer
 * - `scope` and `msg` must be valid null-terminated UTF-8 strings
 *
 * # Arguments
 * * `ctx` - Logger context
 * * `level` - Log level (0=trace, 1=debug, 2=info, 3=warn, 4=error)
 * * `scope` - Log scope/category (e.g., "NET", "DB", "MAIN")
 * * `msg` - Log message
 */
void hyprlog_log(struct HyprlogContext *ctx, int level, const char *scope, const char *msg);

/**
 * Logs a trace message.
 *
 * # Safety
 * See `hyprlog_log`.
 */
void hyprlog_trace(struct HyprlogContext *ctx, const char *scope, const char *msg);

/**
 * Logs a debug message.
 *
 * # Safety
 * See `hyprlog_log`.
 */
void hyprlog_debug(struct HyprlogContext *ctx, const char *scope, const char *msg);

/**
 * Logs an info message.
 *
 * # Safety
 * See `hyprlog_log`.
 */
void hyprlog_info(struct HyprlogContext *ctx, const char *scope, const char *msg);

/**
 * Logs a warning message.
 *
 * # Safety
 * See `hyprlog_log`.
 */
void hyprlog_warn(struct HyprlogContext *ctx, const char *scope, const char *msg);

/**
 * Logs an error message.
 *
 * # Safety
 * See `hyprlog_log`.
 */
void hyprlog_error(struct HyprlogContext *ctx, const char *scope, const char *msg);

/**
 * Retrieves the last error message.
 *
 * # Safety
 * - `ctx` must be a valid context pointer
 * - `buffer` must point to a writable buffer of at least `len` bytes
 *
 * # Returns
 * - Length of error message on success
 * - 0 if no error
 * - -1 on invalid arguments
 */
int hyprlog_get_last_error(struct HyprlogContext *ctx, char *buffer, size_t len);

/**
 * Flushes all log outputs.
 *
 * # Safety
 * `ctx` must be a valid context pointer.
 *
 * # Returns
 * 0 on success, non-zero on error.
 */
int hyprlog_flush(struct HyprlogContext *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* HYPRLOG_H */
